server:
  port: 8761

spring:
  application:
    name: netflix-eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
